= Add your folder to GitHub

=== 1. Create a new repository on GitHub

=== 2. Create and go to new working folder for GitHub
 name it the name of your repository
 sudo git init # to initialize the directory

=== 3. Add your new files
 git add .

=== 4. Commit the files you've staged
 sudo git commit -m "First commit"

=== 5. Copy the Repository URL

=== 6. Add remote repository where local repository is pushed to
 sudo git remote add origin #remote repository URL
 sudo git remote -v # verifies the new remote url

=== 7. Pushes Changes
 sudo git push origin master

=== 8. If Error Featch and Merge
 sudo git fetch origin
 sudo git merge origin #YOUR_BRANCH_NAME 
 # Merge updates online with local work.

=== 9. Or use git pull to before both at once
 sudo git pull origin Your_Branch_Name example: origin master

=== 10. HOW TO DELETE ITEM OFF GITHUB
==== Remove Item from Repository Only
 git rm --cached file1.txt
 git push origin branch_name  #master

=== 11. Git RM for both local and github
 git rm file1.txt
 git commit -m "remove file1.txt"
 git push origin master

= Quick Notes:  

=== Update the Local Repository Files from GitHub
* git pull origin master








