= How to connect to my GitHub repositories from Terminal
== Quick SetUp Guide

Source: https://www.howtoforge.com/tutorial/install-git-and-github-on-ubuntu-14.04/

You will be:

1. Creating a repository locally
2. Connecting this repo to the remote host that contains your project
(where everyone can see)
3. Committing the changes and pushing all content from the local system to 
GitHub.

NOTE: Make sure you registry at GitHub (your email may be public) and know your GitHub user name.

= Installing Git for Linux
 sudo apt-get install git

= Configuring GitHub
Use two commands by replacing "user_name" with your GitHub username and replacing "email_id" with your email-id you used to create your GitHub account.

 git config --global user.name "user_name"

 git config --global user.email "email_id"

Note: Include the quotes.

= Creating a local repository (folder)

 git init nameofrepository 
 
 git init nameofrepository

 cd folder (that you created)

= Create a README file to describe the repository
gedit README

= Adding repository files to an index

Step 1: Adding files to the index.

 git add README

 git add sampleprogram

(index refers to a buffer space of files waiting to be added to GitHub -
I also heard it called a staging area)

= Committing changes made to the index

Step 2: Once all the files added you can commit it.
This means changes are done and ready to upload to GitHub

 git commit -m "some_custom_message"

= Creating a repository on GitHub

Step 3: Create te Repositories on GitHub

Create a repository on GitHub. Notice that the name of the repository should be the same as the repository's on the local system. In this case, it will be "Mytest". To do this login to your account on https://github.com. Then click on the "plus(+)" symbol at the top right corner of the page and select "create new repository". Fill the details as shown in the image below and click on "create repository" button.

Step 4: Connect to the repositorie on GitHub
 git remote add origin https://github.com/user_name/foldername

= Pushing Files in Local Repostory to GitHub Repository
 git push origin master
(we added out content from our folder to github)





