=== Title: tmux_vim_mesh.adoc (notes setup instructions for tmux and vim)

=== By: @mockra_ 

=== Source Link: 
http://mockra.com/2017/05/04/tmux-vim



===  Tmux and Vim Setup

----

// add commands to ~/.tmux.conf file. Adds ability to seamlessly switch between vim and tmux panes using a control + movement key(hjkl).
# smart pane switching with awareness of vim splits
  bind -n C-h run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-h) || tmux select-pane -L"
  bind -n C-j run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-j) || tmux select-pane -D"
  bind -n C-k run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-k) || tmux select-pane -U"
  bind -n C-l run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys C-l) || tmux select-pane -R"
  bind -n C-\ run "(tmux display-message -p '#{pane_current_command}' | grep -iq vim && tmux send-keys 'C-\\') || tmux select-pane -l"


// Next, Install a vim plugin
Plug 'christoomey/vim-tmux-navigator'


// Install Vimux, which will let you easily interact with tmux from vim.
Plug 'benmills/vimux'


// Next, setup our testrunner to take advantage of tmux.
let test#strategy = "vimux"


// setup a shortcut for quickly fullscreening our vimux pane 
map <Leader>z :VimuxZoomRunner<CR>


// mockra's dotfiles for further learning
https://github.com/mockra/dotfiles





